### ISSUE TITLE
How can i monitor the c/c++ application, like thrfit c/c++ client application, thank you

### ISSUE THREAD

**Issue by tianxiaweigong** [naver/pinpoint-c-agent#72]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting

# Current Behavior

> What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:

* PHP Version:

* php.ini:

* php-fpm or apache:

* pinpoint_agent.conf:

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

**Comment by ChenGXQQ** [comment]
pinpoint_common is a pinpoint agent written by C/C++ which communication with pinpoint collector. Because there is no graceful method to AOP C/C++ applications, you can embed this agent in your application and collect information by youself, then send them to collector. You can refer to our PHP implement. By the way, please see the code in nginx and apache folders. Though we have abandoned them, they are still good examples how to use this agent.

**Comment by eeliu** [comment]
It looks had done.
